"""rename gmail_accounts to google_accounts

Revision ID: 04fae5bcfee0
Revises: 42969df49bac
Create Date: 2026-03-06 16:35:29.755710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04fae5bcfee0'
down_revision: Union[str, Sequence[str], None] = '42969df49bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_accounts',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_google_accounts_agent_id'), 'google_accounts', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_gmail_accounts_agent_id'), table_name='gmail_accounts')
    op.drop_table('gmail_accounts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_accounts',
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expiry', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('gmail_accounts_pkey'))
    )
    op.create_index(op.f('ix_gmail_accounts_agent_id'), 'gmail_accounts', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_google_accounts_agent_id'), table_name='google_accounts')
    op.drop_table('google_accounts')
    # ### end Alembic commands ###
