"""Add integrations

Revision ID: 14a1e70239fb
Revises: ee960ca874f5
Create Date: 2026-02-28 17:20:49.734879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14a1e70239fb'
down_revision: Union[str, Sequence[str], None] = 'ee960ca874f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'error', name='integration_status'), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('auth_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('endpoints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_instructions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_integrations_name'), 'global_integrations', ['name'], unique=True)
    op.create_table('agent_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['global_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_integrations_agent_id'), 'agent_integrations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_integrations_integration_id'), 'agent_integrations', ['integration_id'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['global_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_agent_id'), 'integration_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_integration_id'), 'integration_logs', ['integration_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_logs_integration_id'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_agent_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_agent_integrations_integration_id'), table_name='agent_integrations')
    op.drop_index(op.f('ix_agent_integrations_agent_id'), table_name='agent_integrations')
    op.drop_table('agent_integrations')
    op.drop_index(op.f('ix_global_integrations_name'), table_name='global_integrations')
    op.drop_table('global_integrations')
    # ### end Alembic commands ###
