"""added org id to global context

Revision ID: 2aefa65b6d94
Revises: fee82e164e1c
Create Date: 2026-03-18 09:00:57.906551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aefa65b6d94'
down_revision: Union[str, Sequence[str], None] = 'fee82e164e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_contexts', sa.Column('org_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_global_contexts_name'), table_name='global_contexts')
    op.create_index(op.f('ix_global_contexts_name'), 'global_contexts', ['name'], unique=False)
    op.create_index('ix_global_contexts_org_id', 'global_contexts', ['org_id'], unique=False)
    op.create_unique_constraint('uq_global_context_name_org', 'global_contexts', ['name', 'org_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_global_context_name_org', 'global_contexts', type_='unique')
    op.drop_index('ix_global_contexts_org_id', table_name='global_contexts')
    op.drop_index(op.f('ix_global_contexts_name'), table_name='global_contexts')
    op.create_index(op.f('ix_global_contexts_name'), 'global_contexts', ['name'], unique=True)
    op.drop_column('global_contexts', 'org_id')
    # ### end Alembic commands ###
