"""Add cron pipeline runs table

Revision ID: 32da008cd8a9
Revises: eb26bff8f6c7
Create Date: 2026-02-27 16:25:23.261889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32da008cd8a9'
down_revision: Union[str, Sequence[str], None] = 'eb26bff8f6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_pipeline_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cron_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.BigInteger(), nullable=True),
    sa.Column('finished_at', sa.BigInteger(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('global_integrations', sa.JSON(), nullable=True),
    sa.Column('global_context_sources', sa.JSON(), nullable=True),
    sa.Column('raw_summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cron_id'], ['cron_ownership.cron_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_pipeline_runs_cron_id'), 'cron_pipeline_runs', ['cron_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cron_pipeline_runs_cron_id'), table_name='cron_pipeline_runs')
    op.drop_table('cron_pipeline_runs')
    # ### end Alembic commands ###
