"""hardcoded_integrations_v2

Revision ID: 42969df49bac
Revises: c39b48275da0
Create Date: 2026-03-06 16:16:52.084746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42969df49bac'
down_revision: Union[str, Sequence[str], None] = 'c39b48275da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_global_integrations_name'), table_name='global_integrations')
    op.add_column('agent_integrations', sa.Column('integration_name', sa.String(), server_default='legacy', nullable=False))
    op.drop_index(op.f('ix_agent_integrations_integration_id'), table_name='agent_integrations')
    op.create_index(op.f('ix_agent_integrations_integration_name'), 'agent_integrations', ['integration_name'], unique=False)
    op.drop_constraint(op.f('agent_integrations_integration_id_fkey'), 'agent_integrations', type_='foreignkey')
    op.drop_column('agent_integrations', 'integration_id')
    op.add_column('cron_template_integrations', sa.Column('integration_name', sa.String(), server_default='legacy', nullable=False))
    op.drop_constraint(op.f('cron_template_integrations_integration_id_fkey'), 'cron_template_integrations', type_='foreignkey')
    op.drop_column('cron_template_integrations', 'integration_id')
    op.add_column('integration_logs', sa.Column('integration_name', sa.String(), server_default='legacy', nullable=False))
    op.add_column('integration_logs', sa.Column('request_id', sa.String(), nullable=True))
    op.add_column('integration_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_integration_logs_integration_id'), table_name='integration_logs')
    op.create_index(op.f('ix_integration_logs_integration_name'), 'integration_logs', ['integration_name'], unique=False)
    op.drop_constraint(op.f('integration_logs_integration_id_fkey'), 'integration_logs', type_='foreignkey')
    op.drop_column('integration_logs', 'integration_id')
    op.drop_table('global_integrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integration_logs', sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('integration_logs_integration_id_fkey'), 'integration_logs', 'global_integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_integration_logs_integration_name'), table_name='integration_logs')
    op.create_index(op.f('ix_integration_logs_integration_id'), 'integration_logs', ['integration_id'], unique=False)
    op.drop_column('integration_logs', 'error_message')
    op.drop_column('integration_logs', 'request_id')
    op.drop_column('integration_logs', 'integration_name')
    op.add_column('cron_template_integrations', sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('cron_template_integrations_integration_id_fkey'), 'cron_template_integrations', 'global_integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cron_template_integrations', 'integration_name')
    op.add_column('agent_integrations', sa.Column('integration_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('agent_integrations_integration_id_fkey'), 'agent_integrations', 'global_integrations', ['integration_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_integrations_integration_name'), table_name='agent_integrations')
    op.create_index(op.f('ix_agent_integrations_integration_id'), 'agent_integrations', ['integration_id'], unique=False)
    op.drop_column('agent_integrations', 'integration_name')
    op.create_table('global_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'inactive', 'error', name='integration_status'), autoincrement=False, nullable=False),
    sa.Column('base_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('auth_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('endpoints', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('usage_instructions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('auth_scheme', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('api_type', sa.VARCHAR(), server_default=sa.text("'rest'::character varying"), autoincrement=False, nullable=False),
    sa.Column('request_transformers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('response_transformers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('global_integrations_pkey'))
    )
    op.create_index(op.f('ix_global_integrations_name'), 'global_integrations', ['name'], unique=True)
    # ### end Alembic commands ###
