"""add agent_activities table

Revision ID: 558c75046bb6
Revises: 26bd9a7d3627
Create Date: 2026-04-04 09:57:01.026052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '558c75046bb6'
down_revision: Union[str, Sequence[str], None] = '26bd9a7d3627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_activities_activity_type'), 'agent_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_agent_activities_agent_id'), 'agent_activities', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_activities_created_at'), 'agent_activities', ['created_at'], unique=False)
    op.create_index('ix_agent_activity_agent_created', 'agent_activities', ['agent_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_activity_agent_created', table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_created_at'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_agent_id'), table_name='agent_activities')
    op.drop_index(op.f('ix_agent_activities_activity_type'), table_name='agent_activities')
    op.drop_table('agent_activities')
    # ### end Alembic commands ###
