"""Add auth scheme to integration

Revision ID: 5b113e52f9c4
Revises: 14a1e70239fb
Create Date: 2026-02-28 17:53:27.839158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b113e52f9c4'
down_revision: Union[str, Sequence[str], None] = '14a1e70239fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_integrations', sa.Column('auth_scheme', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_integrations', 'auth_scheme')
    # ### end Alembic commands ###
