"""add_gmail_sync_state

Revision ID: 65cba403ee7a
Revises: f3a2c1b4d5e6
Create Date: 2026-03-10 17:25:57.854544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cba403ee7a'
down_revision: Union[str, Sequence[str], None] = 'f3a2c1b4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_sync_state',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_fetched', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_gmail_sync_state_agent_id'), 'gmail_sync_state', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_sync_state_agent_id'), table_name='gmail_sync_state')
    op.drop_table('gmail_sync_state')
    # ### end Alembic commands ###
