"""Relational mappings for cron templates

Revision ID: 6c86a4f35e58
Revises: e11bed24317f
Create Date: 2026-03-01 22:25:51.185811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c86a4f35e58'
down_revision: Union[str, Sequence[str], None] = 'e11bed24317f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_template_integrations',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('integration_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['global_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['cron_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'integration_id')
    )
    op.drop_column('cron_templates', 'required_integrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_templates', sa.Column('required_integrations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('cron_template_integrations')
    # ### end Alembic commands ###
