"""add_failed_ingestions_and_sync_version

Revision ID: 6ec606f03dbb
Revises: cb9e4f158934
Create Date: 2026-03-24 22:55:25.294873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec606f03dbb'
down_revision: Union[str, Sequence[str], None] = 'cb9e4f158934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_ingestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('integration_name', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_retried_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_ingestions_agent_id'), 'failed_ingestions', ['agent_id'], unique=False)
    op.create_index('ix_failed_ingestions_agent_integration', 'failed_ingestions', ['agent_id', 'integration_name'], unique=False)
    op.create_index(op.f('ix_failed_ingestions_integration_name'), 'failed_ingestions', ['integration_name'], unique=False)
    op.create_index(op.f('ix_failed_ingestions_status'), 'failed_ingestions', ['status'], unique=False)
    op.create_index('ix_failed_ingestions_status_retry', 'failed_ingestions', ['status', 'retry_count'], unique=False)
    op.add_column('integration_sync_state', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integration_sync_state', 'version')
    op.drop_index('ix_failed_ingestions_status_retry', table_name='failed_ingestions')
    op.drop_index(op.f('ix_failed_ingestions_status'), table_name='failed_ingestions')
    op.drop_index(op.f('ix_failed_ingestions_integration_name'), table_name='failed_ingestions')
    op.drop_index('ix_failed_ingestions_agent_integration', table_name='failed_ingestions')
    op.drop_index(op.f('ix_failed_ingestions_agent_id'), table_name='failed_ingestions')
    op.drop_table('failed_ingestions')
    # ### end Alembic commands ###
