"""add_cron_ownership_table

Revision ID: 86616a436480
Revises: bbc769909505
Create Date: 2026-02-26 16:22:43.380418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86616a436480'
down_revision: Union[str, Sequence[str], None] = 'bbc769909505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_ownership',
    sa.Column('cron_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cron_id')
    )
    op.create_index(op.f('ix_cron_ownership_agent_id'), 'cron_ownership', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cron_ownership_session_id'), 'cron_ownership', ['session_id'], unique=False)
    op.create_index(op.f('ix_cron_ownership_user_id'), 'cron_ownership', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cron_ownership_user_id'), table_name='cron_ownership')
    op.drop_index(op.f('ix_cron_ownership_session_id'), table_name='cron_ownership')
    op.drop_index(op.f('ix_cron_ownership_agent_id'), table_name='cron_ownership')
    op.drop_table('cron_ownership')
    # ### end Alembic commands ###
