"""cost in tables

Revision ID: b98e7173f755
Revises: 4fef442b3f71
Create Date: 2026-03-16 11:19:12.758012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b98e7173f755'
down_revision: Union[str, Sequence[str], None] = '4fef442b3f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_usage_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('input_cost', sa.Float(), nullable=False),
    sa.Column('output_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_usage_logs_agent_id'), 'chat_usage_logs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chat_usage_logs_message_id'), 'chat_usage_logs', ['message_id'], unique=True)
    op.create_index(op.f('ix_chat_usage_logs_model'), 'chat_usage_logs', ['model'], unique=False)
    op.create_index(op.f('ix_chat_usage_logs_session_id'), 'chat_usage_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_usage_logs_user_id'), 'chat_usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_usage_logs_user_id'), table_name='chat_usage_logs')
    op.drop_index(op.f('ix_chat_usage_logs_session_id'), table_name='chat_usage_logs')
    op.drop_index(op.f('ix_chat_usage_logs_model'), table_name='chat_usage_logs')
    op.drop_index(op.f('ix_chat_usage_logs_message_id'), table_name='chat_usage_logs')
    op.drop_index(op.f('ix_chat_usage_logs_agent_id'), table_name='chat_usage_logs')
    op.drop_table('chat_usage_logs')
    # ### end Alembic commands ###
