"""add_third_party_context_assignments_table

Revision ID: bdfd0a473ec2
Revises: 0eac4608682e
Create Date: 2026-03-11 22:20:57.737666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdfd0a473ec2'
down_revision: Union[str, Sequence[str], None] = '0eac4608682e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('third_party_context_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['third_party_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_third_party_context_assignments_agent_id'), 'third_party_context_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_third_party_context_assignments_context_id'), 'third_party_context_assignments', ['context_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_third_party_context_assignments_context_id'), table_name='third_party_context_assignments')
    op.drop_index(op.f('ix_third_party_context_assignments_agent_id'), table_name='third_party_context_assignments')
    op.drop_table('third_party_context_assignments')
    # ### end Alembic commands ###
