"""add agent registry

Revision ID: bfe6c3e4a4d1
Revises: c91a3f2e5d84
Create Date: 2026-03-17 20:00:50.258345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe6c3e4a4d1'
down_revision: Union[str, Sequence[str], None] = 'c91a3f2e5d84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('workspace', sa.String(), nullable=True),
    sa.Column('agent_dir', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_registry_agent_id'), 'agent_registry', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agent_registry_org_id'), 'agent_registry', ['org_id'], unique=False)
    op.create_index('ix_agent_registry_org_id_agent_id', 'agent_registry', ['org_id', 'agent_id'], unique=False)
    op.create_index(op.f('ix_agent_registry_user_id'), 'agent_registry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_registry_user_id'), table_name='agent_registry')
    op.drop_index('ix_agent_registry_org_id_agent_id', table_name='agent_registry')
    op.drop_index(op.f('ix_agent_registry_org_id'), table_name='agent_registry')
    op.drop_index(op.f('ix_agent_registry_agent_id'), table_name='agent_registry')
    op.drop_table('agent_registry')
    # ### end Alembic commands ###
