"""cost in cron runs

Revision ID: c7d4a42bf03f
Revises: b98e7173f755
Create Date: 2026-03-16 12:37:34.406901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d4a42bf03f'
down_revision: Union[str, Sequence[str], None] = 'b98e7173f755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_pipeline_runs', sa.Column('input_cost', sa.Float(), nullable=True))
    op.add_column('cron_pipeline_runs', sa.Column('output_cost', sa.Float(), nullable=True))
    op.add_column('cron_pipeline_runs', sa.Column('total_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cron_pipeline_runs', 'total_cost')
    op.drop_column('cron_pipeline_runs', 'output_cost')
    op.drop_column('cron_pipeline_runs', 'input_cost')
    # ### end Alembic commands ###
