"""modifications

Revision ID: cb9e4f158934
Revises: a1b2c3d4e5f6
Create Date: 2026-03-18 21:07:57.661140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb9e4f158934'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    NOTE: integration_sync_state creation and gmail_sync_state drop were
    already handled by the previous migration (a1b2c3d4e5f6).  This
    revision only needs to drop calendar_sync_state.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing = inspector.get_table_names()

    if "calendar_sync_state" in existing:
        op.drop_index(op.f('ix_calendar_sync_state_agent_id'), table_name='calendar_sync_state')
        op.drop_table('calendar_sync_state')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_sync_state',
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sync_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_fetched', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('calendar_sync_state_pkey'))
    )
    op.create_index(op.f('ix_calendar_sync_state_agent_id'), 'calendar_sync_state', ['agent_id'], unique=False)
    op.create_table('gmail_sync_state',
    sa.Column('agent_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('history_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_fetched', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('gmail_sync_state_pkey'))
    )
    op.create_index(op.f('ix_gmail_sync_state_agent_id'), 'gmail_sync_state', ['agent_id'], unique=False)
    op.drop_index(op.f('ix_integration_sync_state_agent_id'), table_name='integration_sync_state')
    op.drop_table('integration_sync_state')
    # ### end Alembic commands ###
