"""Add CronTemplate model

Revision ID: e11bed24317f
Revises: 5b113e52f9c4
Create Date: 2026-03-01 14:59:08.299523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11bed24317f'
down_revision: Union[str, Sequence[str], None] = '5b113e52f9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('required_integrations', sa.JSON(), nullable=True),
    sa.Column('variables', sa.JSON(), nullable=True),
    sa.Column('schedule_kind', sa.String(), nullable=False),
    sa.Column('schedule_expr', sa.String(), nullable=False),
    sa.Column('schedule_tz', sa.String(), nullable=True),
    sa.Column('schedule_human', sa.String(), nullable=True),
    sa.Column('session_target', sa.String(), nullable=False),
    sa.Column('delivery_mode', sa.String(), nullable=False),
    sa.Column('payload_message', sa.Text(), nullable=False),
    sa.Column('pipeline_template', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_templates_created_by_user_id'), 'cron_templates', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_cron_templates_is_public'), 'cron_templates', ['is_public'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cron_templates_is_public'), table_name='cron_templates')
    op.drop_index(op.f('ix_cron_templates_created_by_user_id'), table_name='cron_templates')
    op.drop_table('cron_templates')
    # ### end Alembic commands ###
