"""add_agent_tasks_table

Revision ID: eb26bff8f6c7
Revises: 86616a436480
Create Date: 2026-02-26 18:27:15.550238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb26bff8f6c7'
down_revision: Union[str, Sequence[str], None] = '86616a436480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', 'error', name='task_status'), nullable=False),
    sa.Column('difficulty', sa.Enum('low', 'medium', 'high', name='task_difficulty'), nullable=False),
    sa.Column('sub_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('integrations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tasks_agent_id'), 'agent_tasks', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tasks_agent_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    # ### end Alembic commands ###
