"""Add contexts

Revision ID: ee960ca874f5
Revises: 32da008cd8a9
Create Date: 2026-02-28 14:20:31.003288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee960ca874f5'
down_revision: Union[str, Sequence[str], None] = '32da008cd8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_contexts_name'), 'global_contexts', ['name'], unique=True)
    op.create_table('agent_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('context_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['global_contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_contexts_agent_id'), 'agent_contexts', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_contexts_context_id'), 'agent_contexts', ['context_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_contexts_context_id'), table_name='agent_contexts')
    op.drop_index(op.f('ix_agent_contexts_agent_id'), table_name='agent_contexts')
    op.drop_table('agent_contexts')
    op.drop_index(op.f('ix_global_contexts_name'), table_name='global_contexts')
    op.drop_table('global_contexts')
    # ### end Alembic commands ###
