"""add orgid to template

Revision ID: fee82e164e1c
Revises: bfe6c3e4a4d1
Create Date: 2026-03-17 20:30:00.798022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee82e164e1c'
down_revision: Union[str, Sequence[str], None] = 'bfe6c3e4a4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cron_templates', sa.Column('org_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_cron_templates_org_id'), 'cron_templates', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cron_templates_org_id'), table_name='cron_templates')
    op.drop_column('cron_templates', 'org_id')
    # ### end Alembic commands ###
